# Generated by Django 5.0.3 on 2024-04-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about_sociallink_alter_blog_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_decription',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
