# Generated by Django 5.0.3 on 2024-04-04 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
