# Generated by Django 5.0.3 on 2024-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blog_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_descrip',
            field=models.TextField(max_length=4000),
        ),
    ]
