# Generated by Django 5.0.3 on 2024-04-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_about_about_descrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d'),
        ),
    ]
